# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 04:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotYield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LAT', models.FloatField(null=True)),
                ('LONG', models.FloatField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('SoilType', models.CharField(max_length=100)),
                ('SoilTexture_cls', models.CharField(max_length=100, null=True)),
                ('ClayRatio', models.IntegerField(null=True)),
                ('SOM', models.FloatField(null=True)),
                ('TillPractice', models.CharField(max_length=100, null=True)),
                ('TillType', models.CharField(max_length=100, null=True)),
                ('PrevCrop', models.CharField(max_length=100, null=True)),
                ('PrevContribN_cls', models.CharField(max_length=100, null=True)),
                ('PrevContribN_int', models.IntegerField(null=True)),
                ('CHU', models.IntegerField(null=True)),
                ('PPT', models.IntegerField(null=True)),
                ('AWDR', models.FloatField(null=True)),
                ('Nrate', models.IntegerField()),
                ('Yield', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site_Field', models.CharField(max_length=200)),
                ('BDoriginale', models.CharField(max_length=100)),
                ('Province', models.CharField(max_length=100)),
                ('Region', models.CharField(max_length=200)),
                ('Town', models.CharField(max_length=100)),
                ('Site', models.CharField(max_length=100)),
                ('Field', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRquestSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer', models.CharField(max_length=100)),
                ('current_crop', models.CharField(max_length=100)),
                ('season', models.IntegerField()),
                ('soiltype', models.CharField(max_length=100)),
                ('tilltype', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('climate', models.CharField(max_length=100)),
                ('prev_crop', models.CharField(max_length=100)),
                ('price_mean', models.FloatField(null=True)),
                ('price_std', models.FloatField(null=True)),
                ('costmean', models.FloatField(null=True)),
                ('coststd', models.FloatField(null=True)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('retry_count', models.IntegerField(default=0, null=True)),
                ('isEmailSent', models.CharField(default='N', max_length=1)),
                ('request_process_time', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usersite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dssservice.UserRquestSite', verbose_name='user request site to user trans mapping')),
            ],
        ),
        migrations.AddField(
            model_name='plotyield',
            name='SiteFieldId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dssservice.SiteField'),
        ),
    ]
